version: '3.9'

services:

  app :
    container_name: go-container
    build:
      context: .
      dockerfile: Dockerfile
      target : dev 
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - .:/app
